### ISSUE TITLE
More detalied use for onemetric

### ISSUE THREAD

**Issue by kascesar** [SkalskiP/onemetric#7]
Hi, im interesting in this project, but i dont now how to send the batches to mAP metric for yolo.
my **yolo v2 generator** generate batches like (batch_size, 13, 13, 5, 4 + 1 + n_classes), and the **net** produce a output shape like ground truth (batch_size, 13, 13, 5, 4 + 1 + n_classes). If i try **onemetric** it will be works well ? 

And if i do with a yolov3 or yolov4 model ? it work to ? or only work with DarkNet api ? im build all in TF. 
Thks a lot!

**Comment by SkalskiP** [comment]
Hello, @kascesar yup it should work :) what yolov3 implementation are you using? https://github.com/ultralytics/yolov3 ?

**Comment by kascesar** [comment]
Thnks, i will be implemented in the near future. but, wee understand that the yolo out put are:
`3 x (bz, gridX, gridY, n_ anchors, 4 + 1 + n_classes)`.
This work with this 3 head output as defect? or we need to do some code ?

**Comment by SkalskiP** [comment]
@kascesar It will work, there will only be a need for a small function to going from your detection tensor to the required format. That should be easy.
