### ISSUE TITLE
ModuleNotFoundError when installing with pip

### ISSUE THREAD

**Issue by bindas1** [SkalskiP/onemetric#8]
**Describe the bug**
If installing the package with pip I can;t use the module MeanAveragePrecision. I receive the following error:
```ModuleNotFoundError: No module named 'onemetric.cv.object_detection'; 'onemetric.cv' is not a package```
It works if I download the repository and install using `setup.py`

**Screenshots**
![image](https://user-images.githubusercontent.com/38891725/146642814-57a3d10e-2522-4243-9af3-98ea8788f5b5.png)

**Environment**
- OS: Ubuntu 20.04
- Python Version: 3.8.11
- onemetric Version: 0.1.1

**Comment by SkalskiP** [comment]
Hello @bindas1 👋 ! I’ll take care of that. Thanks for letting me know.

**Comment by bindas1** [comment]
I'm not sure why but I managed to solve this by running `pip install --upgrade onemetric` instead of `pip install onemetric`. 
Thanks for the library, it's really useful. :)

**Comment by SkalskiP** [comment]
Hello @bindas1 👋  ! Thank you very much for your interest in my little project. If you have any idea what else I could add just let me know! 🧐  I will add this additional command in the installation instructions so that other users don't have this problem.

**Comment by bindas1** [comment]
I've managed to recreate the same issue in my Windows 11. In this OS despite using both methods of installation I can't get it to work.
For ideas for now I think it may be useful and easy to just extend onemetric to also include precision/recall plot and return the metrics unless it's been already implemented. I'll think of some more usecases.

**Comment by SkalskiP** [comment]
Hello @bindas1! Thank you for testing it on other operating systems. In that case, I'll take a look at that problem between Christmas and New Year. I have Windows 11 on my PC. I barely use it, but it should work just fine as a test environment. In the meantime can you share the error you are getting on Windows in both cases? Or is it exactly the same you posted in the first message? 

Precision and recall visualizations are definitely on my list. ;)

**Comment by bindas1** [comment]
The error message was exactly the same, just make sure to use a fresh conda environment with newly installed library. :)

**Comment by SkalskiP** [comment]
@bindas1 so you are using conda env not python venv to set it up?

**Comment by bindas1** [comment]
Yes, I am using conda env, if you want I can give you my yaml file, but the python distro on both os was 3.8.11 as specifed above

**Comment by bindas1** [comment]
I believe I may have found the origin of this error - if installing by pip / conda `onemetric.cv ` isn't a package as the error says because there exists a file `~/envs/yolo/lib/python3.8/site-packages/onemetric/cv.py`
<img width="830" alt="image" src="https://user-images.githubusercontent.com/38891725/147409679-2288c164-759c-4b53-a945-327833651e5e.png">

<img width="564" alt="image" src="https://user-images.githubusercontent.com/38891725/147409690-c0085647-8284-4a2a-943a-e472280b9438.png">

Error messages from WSL using conda environment.

**Comment by SkalskiP** [comment]
@bindas1 I know it took much more than expected but the bug is fixed and now you should be able to correctly install and import parts of `onemetric` package.
